version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - run:
          name: Install Dependencies (next-redux1)
          working_directory: next-redux1
          command: npm install
      - run:
          name: Run tests (next-redux1)
          working_directory: next-redux1
          command: npm run test
      - run:
          name: Install Dependencies (next-redux2)
          working_directory: next-redux2
          command: npm install
      - run:
          name: Run tests (next-redux2)
          working_directory: next-redux2
          command: npm run test