name: Jest

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies (next-redux1)
        run: npm install
        working-directory: ./next-redux1
      - name: Run test (next-redux1)
        run: npm test
        working-directory: ./next-redux1
      - name: Install Dependencies (next-redux2)
        run: npm install
        working-directory: ./next-redux2
      - name: Run test (next-redux2)
        run: npm test
        working-directory: ./next-redux2